### ISSUE TITLE
Quiz Lv3 Feedback

### ISSUE THREAD

**Issue by udiiin** [harikuswanto/quiz-3#1]
Terima kasih utk submissionnya Mas @harikuswanto.  
Saya ada beberapa feedback:

**1.)**  
Pada fungsi `loadMore`, terdapat manipulasi DOM secara langsung.
```js
const loadButton = document.getElementById('loadMore');
loadButton.innerHTML='Loading...';
```
Ini merupakan pattern yg perlu dihindari.  
Manfaatkan state saja mas..

**2.)**  
Saat membuka homepage, button filter "New" dibuat otomatis sudah aktif (warna merah) saja mas, sesuai Figma.

**3.)**  
Fungsi `sortPosts` tidak perlu dipassing lewat props dari page sampai component `Sorter`.  
(Istilahnya _prop-drilling_)  
Bisa langsung bikin fungsi `sortPosts` di dalam component `Sorter`.

**4.)**  
URL `https://hsi-sandbox.vercel.app/api` bisa disimpan ke dalam variable, kemudian diexport.  
Jadi di tiap component yg menggunakannya tinggal import saja variable tsb, tdk perlu menuliskan URL berkali-kali.

**5.)**  
`/api/hello.js` tidak dipakai, bisa dihapus saja

.

Barokallaahu fiik, semoga dilancarkan 🙏

**Comment by harikuswanto** [comment]
Sudah direvisi mas @udiiin

**Comment by udiiin** [comment]
Sipp mas 👍  
Dari saya udah oke ✅

Barokallaahu fiik
